
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module user_input_buffer(

 //////////// CLOCK //////////
    input               clk,

	 input			clr,
	 
	 input 			rst_n,

 //////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
    inout       [35:0]  GPIO,
	 
	 output up, down, left, right, space
);

reg	[4:0] ops;

assign up = ops[0];
assign down = ops[1];
assign left = ops[2];
assign right = ops[3];
assign space = ops[4];

wire rst;
assign rst = (clr && (ops != 5'b0)) || ~rst_n;

wire txd;
wire rxd;
wire iocs;
wire iorw;
wire rda;
wire tbr;
wire [1:0] ioaddr;
wire [7:0] databus;
wire [1:0] br_cfg;

wire [4:0] get_ops;

always @(posedge clk) begin
	if (rst) begin
		ops = 5'b0;
	end
	if (get_ops != 5'b0) begin
		ops = get_ops | ops;
	end
end

// LED[9] : indicator for RX signal
// LED[8] : indicator for TX signal
// LED[0] : indicator for rst signal 
// assign LEDR = {~rxd,~txd, ops, 2'b0,rst};

// GPIO[3] as TX output, GPIO[5] as RX input
assign GPIO[3] = 1'b1;
assign rxd = GPIO[5];

// slide switch [9:8] as baudrate config
assign br_cfg = 2'b00;

// Instantiate your spart here
spart spart0(   .clk(clk),
                .rst(~rst_n),
                .iocs(iocs),
                .iorw(iorw),
                .rda(rda),
                .tbr(tbr),
                .ioaddr(ioaddr),
                .databus(databus),
                .txd(txd),
                .rxd(rxd)
            );

// Instantiate your driver here
driver driver0( .clk(clk),
                .rst(~rst_n), 
                .br_cfg(br_cfg),
                .iocs(iocs),
                .iorw(iorw),
                .rda(rda),
                .tbr(tbr),
                .ioaddr(ioaddr),
                .databus(databus),
					 .get_ops(get_ops)
            );

		

endmodule
