// soc_audio_lrclk.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module soc_audio_lrclk (
		input  wire  AUD_BCLK,  //  AUD_BCLK.clk
		output wire  AUD_LRCLK, // AUD_LRCLK.clk
		input  wire  clk,       //       clk.clk
		input  wire  reset      //     reset.reset
	);

	soc_audio_lrclk_intel_up_avalon_audio_clks_0 intel_up_avalon_audio_clks_0 (
		.clk       (clk),       //       clk.clk
		.reset     (reset),     //     reset.reset
		.AUD_BCLK  (AUD_BCLK),  //  AUD_BCLK.clk
		.AUD_LRCLK (AUD_LRCLK)  // AUD_LRCLK.clk
	);

endmodule
